### ISSUE TITLE
Doesn't search and gives error

### ISSUE THREAD

**Issue by Lelouchq** [Raihann22/Roblox-Player-Server-Searcher#13]
![image](https://github.com/user-attachments/assets/0666fd6b-312e-4898-ae3d-c720c6fd8ae1)

is there anyway to fix this?

**Comment by Raihann22** [comment]
Looks like the error is happening because the script for fetching the servers hit the Roblox API rate limit (429 Too Many Requests).

![429 Too Many Requests](https://github.com/user-attachments/assets/26149018-4f56-4c68-9bb2-9bcd8dc2fc37)

I think Roblox might've updated their games API and reduced the limit. This is becoming a bigger issue with [Roblox Player Server Searcher](https://github.com/Raihann22/Roblox-Player-Server-Searcher) that need to retrieve all servers—like for Murder Mystery 2, which currently has around 20k servers.

I tested the current code, and it can only pull around 200-300 servers before hitting the limit. 💀

I'll fix the issue as soon as possible, but if anyone can help out in the meantime, I'd be really grateful since I'm pretty busy IRL.

**Comment by Raihann22** [comment]
I think I found the solution, but I'm tied up with other stuff right now. 
I'll try to fix it when I get some free time. 
Hopefully, I can finish it by the end of the week, but I'll do my best to fix it sooner.

**Comment by moxxx3** [comment]
has it been figured out?

**Comment by Raihann22** [comment]
> has it been figured out?

~~Yes, I've figured out the solution and already fixed it since my last reply. I'll release a beta version later to test if it works for other users too before officially releasing it.~~

After looking into it further, I don't think my code actually fixed the issue.
I'm not sure why it seemed to work three days ago—or maybe it didn't?

I'll keep trying to find a solution, but I'm not sure if it's fixable.
Sorry, everyone.

**Comment by LukesConqueror** [comment]
There may be some workaround with it. When it hits the API limit, try waiting for a certain time then let it fetch servers again until the user is found. Won't be as fast as before, but hey at least it works.

**Comment by Raihann22** [comment]
> There may be some workaround with it. When it hits the API limit, try waiting for a certain time then let it fetch servers again until the user is found. Won't be as fast as before, but hey at least it works.

It's hard to implement because Roblox doesn't include the 'x-ratelimit-reset' in the response header, so we don't know when we can make a new request. 

After some tests, it looks like Roblox sets a limit of 3 requests (300 servers) per minute, any more than that will result in a rate limit. 
It takes over 30 minutes to fetch all Murder Mystery 2 servers (if the user isn't found yet).

**Comment by Ravisil** [comment]
> > Pode haver alguma solução alternativa para isso. Quando atingir o limite da API, tente esperar um certo tempo e deixe-o buscar servidores novamente até que o usuário seja encontrado. Não será tão rápido quanto antes, mas, ei, pelo menos funciona.
> 
> É difícil de implementar porque o Roblox não inclui 'x-ratelimit-reset' no cabeçalho de resposta, então não sabemos quando podemos fazer uma nova solicitação.
> 
> Após alguns testes, parece que o Roblox define um limite de 3 requisições (300 servidores) por minuto, mais do que isso resultará em um limite de taxa. Leva mais de 30 minutos para buscar todos os servidores de Murder Mystery 2 (se o usuário ainda não for encontrado).

But does it still work?

**Comment by Raihann22** [comment]
> But does it still work?

Yes, it will work if I move the fetch function to `background.js` and only send 3 requests per minute.

For games with a max of 5 players per server, the old method works and is much faster (I don't think there's a limit).

However, for games with more than 5 players per server, it can only fetch 300 servers per minute. So I don't think it's worth the effort to implement.

**Comment by LukesConqueror** [comment]
I think that may still be worth implementing, no other extension other than this works. Most people I've known with are looking for this as well, just that it doesn't work with games like you said, with many servers. But yeah, we could wait. ❤️

**Comment by Raihann22** [comment]
Can someone try this [v3.0.0-beta1](https://github.com/Raihann22/Roblox-Player-Server-Searcher/releases/tag/v3.0.0-beta1) version, please? 
And don't forget to give me feedback and let me know if it's working or not before I make a full release.

In this version, if the server size is more than 5, it will fetch the Servers API every 20 seconds until it's done.

However, there's a weird bug where sometimes Roblox doesn't return all the servers when fetching, so it might not find the user's server even though the user is in the game. But most of the time, it works.

**If you see an update popup, just close it.**

**Comment by N1bblehead** [comment]
Seems like it works, raihann22. Just tested that version. 

Thank you for making a useful plugin man! :)

**Comment by Raihann22** [comment]
> Seems like it works, raihann22. Just tested that version.
> 
> Thank you for making a useful plugin man! :)

Thank you for letting me know it works on your PC too! 

I'll close this issue. If anyone wants to request a feature, report an issue, or has questions about the 3.0.0-beta version, feel free to comment on [v3.0.0-beta Thread](https://github.com/Raihann22/Roblox-Player-Server-Searcher/issues/20).

**Comment by shawchip** [comment]
> > Seems like it works, raihann22. Just tested that version.
> > Thank you for making a useful plugin man! :)
> 
> Thank you for letting me know it works on your PC too!
> 
> I'll close this issue. If anyone wants to request a feature, report an issue, or has questions about the 3.0.0-beta version, feel free to comment on [v3.0.0-beta Thread](https://github.com/Raihann22/Roblox-Player-Server-Searcher/issues/20).

Does it work now? I hope so, thank you for your amazing plugin

**Comment by FoxVukOff** [comment]
Works fine! Thank you!

**Comment by Raihann22** [comment]
New release! [Version 3.0.1](https://github.com/Raihann22/Roblox-Player-Server-Searcher/releases/tag/v3.0.1)

**Comment by Rewdzi** [comment]
> New release! [Version 3.0.1](https://github.com/Raihann22/Roblox-Player-Server-Searcher/releases/tag/v3.0.1)

It's broken again :p please fix
